version: "3.3"

services:
  comments:
    build:
      context: .
      dockerfile: services/comments/Dockerfile
    env_file:
      - services/comments/.env
    ports:
      - 3009:3009
    restart: on-failure
    links:
      - jaeger
      - psql_comments
      - redis_comments
    depends_on:
      - jaeger
      - psql_comments
      - redis_comments

  psql_comments:
    image: postgres:12.0-alpine
    expose:
      - 5432
    volumes:
      - psql_comments_volume:/var/lib/postgresql/data/
      - ./services/comments/sql/script.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - services/comments/.env

  redis_comments:
    build:
      context: .
      dockerfile: services/comments/.redis/Dockerfile
    expose:
      - 6379

  jaeger:
    image: jaegertracing/all-in-one:latest
    expose:
      - "14269"
      - "5778"
      - "14268"
      - "14267"
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
    ports:
      - 16686:16686

volumes:
  psql_comments_volume: