version: "3.3"

services:
  psql_news:
    image: postgres:12.0-alpine
    expose:
      - 5432
    volumes:
      - psql_news_volume:/var/lib/postgresql/data/
      - ./services/news/sql/script.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - services/news/.env
  redis_news:
    build:
      context: .
      dockerfile: services/news/.redis/Dockerfile
    expose:
      - 6379
  news:
    build:
      context: .
      dockerfile: services/news/Dockerfile
    env_file:
      - services/news/.env
    expose:
      - 3009
    restart: on-failure
    links:
      - jaeger
      - psql_news
      - redis_news
    depends_on:
      - jaeger
      - psql_news
      - redis_news

  accounts:
    build:
      context: .
      dockerfile: services/accounts/Dockerfile
    env_file:
      - services/accounts/.env
    expose:
      - 3009
    restart: on-failure
    links:
      - jaeger
      - psql_accounts
      - redis_accounts
    depends_on:
      - jaeger
      - psql_accounts
      - redis_accounts

  psql_accounts:
    image: postgres:12.0-alpine
    expose:
      - 5432
    volumes:
      - psql_accounts_volume:/var/lib/postgresql/data/
      - ./services/accounts/sql/script.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - services/accounts/.env

  redis_accounts:
    build:
      context: .
      dockerfile: services/accounts/.redis/Dockerfile
    expose:
      - 6379

  comments:
    build:
      context: .
      dockerfile: services/comments/Dockerfile
    env_file:
      - services/comments/.env
    expose:
      - 3009
    restart: on-failure
    links:
      - jaeger
      - psql_comments
      - redis_comments
    depends_on:
      - jaeger
      - psql_comments
      - redis_comments

  psql_comments:
    image: postgres:12.0-alpine
    expose:
      - 5432
    volumes:
      - psql_comments_volume:/var/lib/postgresql/data/
      - ./services/comments/sql/script.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - services/comments/.env

  redis_comments:
    build:
      context: .
      dockerfile: services/comments/.redis/Dockerfile
    expose:
      - 6379
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    env_file:
      - services/gateway/.env
    ports:
      - 8080:8080
    expose:
      - 8080
    restart: on-failure
    links:
      - jaeger
      - comments
      - accounts
      - news
    depends_on:
      - jaeger
      - comments
      - accounts
      - news

  jaeger:
    image: jaegertracing/all-in-one:latest
    expose:
      - "14269"
      - "5778"
      - "14268"
      - "14267"
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
    ports:
      - 16686:16686

volumes:
  psql_comments_volume:
  psql_accounts_volume:
  psql_news_volume: